In [7]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\Lakshmi\Downloads\social_media.csv")

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (1000, 15)

,post_id,platform,post_date,content_type,category,likes,comments,shares,views,reach,hashtags_count,total_engagement,engagement_rate,post_month,post_day
0,1,Instagram,2025-04-10,Image,Technology,2255,265,198,85481,54788,6,2718,4.960940,April,Thursday
1,2,Twitter,2025-04-19,Video,Travel,1279,47,40,61593,52977,7,1366,2.578477,April,Saturday
2,3,Facebook,2025-12-09,Text,Technology,3294,300,56,73075,63099,1,3650,5.784561,December,Tuesday
3,4,Facebook,2025-06-22,Reel,Entertainment,2510,228,105,50522,33043,5,2843,8.603940,June,Sunday
4,5,Instagram,2025-08-25,Reel,Food,392,12,30,5886,3711,14,434,11.694961,August,Monday

In [8]:
print("Dataset Shape:", df.shape)
print("\nColumn Names:")
print(df.columns.tolist())

Dataset Shape: (1000, 15)

Column Names:
['post_id', 'platform', 'post_date', 'content_type', 'category', 'likes', 'comments', 'shares', 'views', 'reach', 'hashtags_count', 'total_engagement', 'engagement_rate', 'post_month', 'post_day']

In [9]:
social = df.copy()
print("Working copy created.")
print("Shape:", social.shape)

Working copy created.
Shape: (1000, 15)

In [10]:
print("Missing Values:")
print(social.isnull().sum())

Missing Values:
post_id             0
platform            0
post_date           0
content_type        0
category            0
likes               0
comments            0
shares              0
views               0
reach               0
hashtags_count      0
total_engagement    0
engagement_rate     0
post_month          0
post_day            0
dtype: int64

In [11]:
print("Duplicate Rows:", social.duplicated().sum())

Duplicate Rows: 0

In [12]:
social["post_date"] = pd.to_datetime(
    social["post_date"],
    errors="coerce"
)
print(social["post_date"].dtype)

datetime64[us]

In [13]:
print(
    social[
        [
            "likes",
            "comments",
            "shares",
            "total_engagement",
            "reach",
            "engagement_rate"
        ]
    ].head()
)

   likes  comments  shares  total_engagement  reach  engagement_rate
0   2255       265     198              2718  54788         4.960940
1   1279        47      40              1366  52977         2.578477
2   3294       300      56              3650  63099         5.784561
3   2510       228     105              2843  33043         8.603940
4    392        12      30               434   3711        11.694961

In [15]:
from sqlalchemy import create_engine
username = "root"
password = "Praba_1910"
host = "localhost"
port = 3306
engine = create_engine(
    f"mysql+pymysql://{username}:{password}@{host}:{port}/social_media_analytics"
)
print("MySQL connection created successfully!")

MySQL connection created successfully!

In [16]:
social.to_sql(
    "social_media_data",
    con=engine,
    if_exists="replace",
    index=False
)
print("Data loaded successfully into MySQL!")

Data loaded successfully into MySQL!

In [17]:
result = pd.read_sql(
    "SELECT COUNT(*) AS total_rows FROM social_media_data",
    engine
)

print(result)

   total_rows
0        1000

In [18]:
mysql_data = pd.read_sql(
    "SELECT * FROM social_media_data LIMIT 5",
    engine
)

mysql_data

,post_id,platform,post_date,content_type,category,likes,comments,shares,views,reach,hashtags_count,total_engagement,engagement_rate,post_month,post_day
0,1,Instagram,2025-04-10,Image,Technology,2255,265,198,85481,54788,6,2718,4.960940,April,Thursday
1,2,Twitter,2025-04-19,Video,Travel,1279,47,40,61593,52977,7,1366,2.578477,April,Saturday
2,3,Facebook,2025-12-09,Text,Technology,3294,300,56,73075,63099,1,3650,5.784561,December,Tuesday
3,4,Facebook,2025-06-22,Reel,Entertainment,2510,228,105,50522,33043,5,2843,8.603940,June,Sunday
4,5,Instagram,2025-08-25,Reel,Food,392,12,30,5886,3711,14,434,11.694961,August,Monday

In [19]:
powerbi_data = pd.read_sql(
    "SELECT * FROM social_media_data",
    engine
)

powerbi_data.to_csv(
    "social_media_powerbi.csv",
    index=False
)

print("Power BI file created!")
print("Rows:", len(powerbi_data))

Power BI file created!
Rows: 1000

In [21]:
import pandas as pd
from sqlalchemy import create_engine

engine = create_engine(
    "mysql+pymysql://root:Praba_1910@localhost:3306/social_media_analytics"
)

df = pd.read_sql("SELECT * FROM social_media_data", engine)

print("Data loaded successfully!")
print(df.shape)

df.head()

Data loaded successfully!
(1000, 15)

,post_id,platform,post_date,content_type,category,likes,comments,shares,views,reach,hashtags_count,total_engagement,engagement_rate,post_month,post_day
0,1,Instagram,2025-04-10,Image,Technology,2255,265,198,85481,54788,6,2718,4.960940,April,Thursday
1,2,Twitter,2025-04-19,Video,Travel,1279,47,40,61593,52977,7,1366,2.578477,April,Saturday
2,3,Facebook,2025-12-09,Text,Technology,3294,300,56,73075,63099,1,3650,5.784561,December,Tuesday
3,4,Facebook,2025-06-22,Reel,Entertainment,2510,228,105,50522,33043,5,2843,8.603940,June,Sunday
4,5,Instagram,2025-08-25,Reel,Food,392,12,30,5886,3711,14,434,11.694961,August,Monday

In [22]:
df.to_csv("social_media_powerbi.csv", index=False)

print("CSV created successfully!")

CSV created successfully!

In [23]:
import os

print(os.getcwd())
print(os.listdir())

C:\Users\Lakshmi
['.copilot', '.idlerc', '.ipynb_checkpoints', '.ipython', '.local', '.streamlit', '.vscode', '.vscode-shared', 'AppData', 'Application Data', 'Contacts', 'Cookies', 'Documents', 'Downloads', 'Favorites', 'Links', 'Local Settings', 'mini proj', 'Music', 'My Documents', 'NetHood', 'NTUSER.DAT', 'ntuser.dat.LOG1', 'ntuser.dat.LOG2', 'NTUSER.DAT{85b45321-eada-11f0-bfd6-c1178bf6dfed}.TM.blf', 'NTUSER.DAT{85b45321-eada-11f0-bfd6-c1178bf6dfed}.TM.blf.cnpf', 'NTUSER.DAT{85b45321-eada-11f0-bfd6-c1178bf6dfed}.TMContainer00000000000000000001.regtrans-ms', 'NTUSER.DAT{85b45321-eada-11f0-bfd6-c1178bf6dfed}.TMContainer00000000000000000001.regtrans-ms.cnpf', 'NTUSER.DAT{85b45321-eada-11f0-bfd6-c1178bf6dfed}.TMContainer00000000000000000002.regtrans-ms', 'NTUSER.DAT{85b45321-eada-11f0-bfd6-c1178bf6dfed}.TMContainer00000000000000000002.regtrans-ms.cnpf', 'ntuser.ini', 'OneDrive', 'PrintHood', 'Recent', 'Saved Games', 'Searches', 'SendTo', 'social_media.csv', 'Social_Media_Analytics.ipynb', 'social_media_powerbi.csv', 'Start Menu', 'Templates', 'Videos']